version: '3.9'

services:
  # Микросервис пользователей
  user-service:
    build:
      context: ./user_service
      dockerfile: ./Dockerfile
    container_name: user-service
    ports:
      - "8001:8000"
    volumes:
      - ./user_service:/app
    environment:
      DB_HOST: ${USER_DB_HOST}
      DB_PORT: ${USER_DB_PORT}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      DB_NAME: ${USER_DB_NAME}
    depends_on:
      - user-db

  # База данных для пользователей
  user-db:
    image: postgres:14
    container_name: user-db
    environment:
      POSTGRES_USER: ${USER_DB_USER}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DB: ${USER_DB_NAME}
    volumes:
      - user_data:/var/lib/postgresql/data
    ports:
      - "54321:5432" 

  # Миграции пользователей
  user-migrate:
    build:
      context: ./user_service
      dockerfile: ./Dockerfile
    command: ["alembic", "upgrade", "head"]
    container_name: user-migrate
    env_file:
      - .env
    environment:
      DB_HOST: ${USER_DB_HOST}
      DB_PORT: ${USER_DB_PORT}
      DB_USER: ${USER_DB_USER}
      DB_PASSWORD: ${USER_DB_PASSWORD}
      DB_NAME: ${USER_DB_NAME}
    depends_on:
      - user-db

  # API Gateway
  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: ./Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - user-service

volumes:
  user_data: